import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';

// Tailwind v4 entry (theme + utilities, NO preflight — see tailwind.css).
// Imported first so its `@layer theme, base, components, utilities` order is
// established before the unlayered project CSS (which always wins the cascade,
// keeping v3 visually identical to v2 until sections are explicitly converted).
import './styles/tailwind.css';

// Global CSS — design tokens + reusable utilities.
// These define `:root` custom properties and global classes
// (.btn, .wc-bgline, .deco) that components consume via plain
// className strings. Component-internal classes are scoped via
// per-component .module.css files instead.
import './styles/reset.css';
import './styles/tokens.css';
import './styles/btn.css';
import './styles/bg-line.css';
import './styles/global.css';
// pages-home.css carries all section-layout rules (.hero-*, .games-*, .fd-*,
// .loc-*, .events-*, .footer-*, etc.). Loading it once here means every
// homepage section gets its layout regardless of per-component .css order.
import './styles/pages-home.css';
// dashboard-edits.css is auto-generated by the Dashboard Edit Tool. It MUST
// be imported LAST so its rules win the cascade over component-intrinsic
// CSS without needing extra specificity. See vite-plugin-edit-persistence.js.
import './styles/dashboard-edits.css';

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>
);
